name: CI

on: [push, pull_request]

jobs:
  kubeaudit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          curl -sLf -o kubeaudit.tar.gz  https://github.com/Shopify/kubeaudit/releases/download/v0.12.0/kubeaudit_0.12.0_linux_amd64.tar.gz
          tar -zxvf kubeaudit.tar.gz
          chmod +x kubeaudit
      - name: audit
        run: ./kubeaudit nonroot -f deployment.yaml
